name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
#导入库，并打开文件
import matplotlib.pyplot as plt
from scipy import optimize as op
import numpy as np
import csv
import pandas as pd
df = pd.read_csv(r'C:\Users\TAO\Desktop\XZ\ShiyanShuju.csv',usecols=["(G0-Gt)/T"],dtype=float)
df2=pd.read_csv(r'C:\Users\TAO\Desktop\XZ\ShiyanShuju.csv',usecols=["Gt"],dtype=float)
print(df)
