name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
import matplotlib.pyplot as plt
from scipy import optimize as op
import numpy as np
import csv
import pandas as pd
df = pd.read_csv(r'C:\Users\TAO\Desktop\XZ\ShiyanShuju.csv',names=["Gt"])
df1 = pd.read_csv(r'C:\Users\TAO\Desktop\XZ\ShiyanShuju.csv',names=["t"])
df2=pd.read_csv(r'C:\Users\TAO\Desktop\XZ\ShiyanShuju.csv',names=["(G0-Gt)/T"])
k1=2079
a=0.00927
kt=np.array(df)
#kt.astype(float)
t=np.array(df1)
y=kt
#kt = kt.astype(np.float)
#kt1 = kt1.astype(np.float)
#it = np.nditer(df)
#for i in range(1):
for j in range(1,5):
    kt[0][j]=float(kt[0][j])
#x_group=x
#y_group=kt
def f_1(x,A,B):
    return A*x+B

A,B=op.curve_fit(f_1,x,y)[0]
plt.scatter(x_group,y_group,marker="*",label='real')
y=A*x+B
plt.plot(x,y,color="red",label="curve_Fit")
plt.legend()
plt.xlabel("(k1-kt)/t")
plt.ylabel("kt")
plt.show()
k=1/(a*A)
print(A)
print(k)
